#https://github.com/CribberSix/docker-compose/blob/main/nifi/docker-compose.yml
version: "3"
services:
  # configuration manager for NiFi
  zookeeper:
    hostname: my_nifi_zookeeper
    container_name: my_nifi_zookeeper
    image: 'bitnami/zookeeper:latest'
    restart: on-failure
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my_persistent_network


  # version control for nifi flows
  registry:
    hostname: my_nifi_registry
    container_name: my_nifi_registry
    image: 'apache/nifi-registry:latest'
    restart: on-failure
    ports:
      - "18080:18080"
    environment:
      - LOG_LEVEL=INFO
    #      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
    #      - NIFI_REGISTRY_FLOW_PROVIDER=file
    #      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    #    volumes:
    #      - ./nifi_registry/database:/opt/nifi-registry/nifi-registry-current/database
    #      - ./nifi_registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
    networks:
      - my_persistent_network


  # data extraction, transformation and load service
  nifi:
    hostname: my_nifi
    container_name: my_nifi
    image: 'apache/nifi:latest'
    restart: on-failure
    ports:
      - 8091:8080
      - 8092:8443
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_ZK_CONNECT_STRING=my_nifi_zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=30 sec
      - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
      - INITIAL_ADMIN_IDENTITY='CN=Random User, O=Apache, OU=NiFi, C=US'
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8091/nifi/}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 5
    volumes:
      - /home/cuong/chinhnq2/nifi/driver:/opt/nifi/nifi-current/driver
    networks:
      - my_persistent_network

networks:
  my_persistent_network:
    driver: bridge
